import avatar from '../../src/img/profilePic.jpg';
import linkedIn from '../../src/img/linkedIn.jpg';

console.log('avatar , linkedIn :', avatar , linkedIn);

const data = [
    {
        uniqueId:"uid1",  
        profile: avatar,
        name: "Abc1Xyz",
        employment: "Engineer1",
        emailId: "abc1@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    },
    {
        uniqueId:"uid2",
        profile: avatar,
        name: "Abc1Xyz",
        employment: "Engineer2",
        emailId: "abc2@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    },
    {
        uniqueId:"uid3",
        profile: avatar,
        name: "Abc2Xyz",
        employment: "Engineer3",
        emailId: "abc3@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    },
    {
        uniqueId:"uid4",
        profile: avatar,
        name: "Abc Xyz",
        employment: "Engineer",
        emailId: "abc4@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    },
    {
        uniqueId:"uid5",
        profile: avatar,
        name: "Abc Xyz",
        employment: "Engineer",
        emailId: "abc5@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    },
    {
        uniqueId:"uid6",
        profile: avatar,
        name: "Abc Xyz",
        employment: "Engineer",
        emailId: "abc6@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    },
    {
        uniqueId:"uid7",
        profile: avatar,
        name: "Abc Xyz",
        employment: "Engineer",
        emailId: "abc7@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    },
    {
        uniqueId:"uid8",
        profile: avatar,
        name: "Abc Xyz",
        employment: "Engineer",
        emailId: "abc8@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    },
    {
        uniqueId:"uid9",
        profile: avatar,
        name: "Abc Xyz",
        employment: "Engineer",
        emailId: "abc9@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    }, 
    {
        uniqueId:"uid10",
        profile: avatar,
        name: "Abc Xyz",
        employment: "Engineer",
        emailId: "abc10@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    },
    {
        uniqueId:"uid11",
        profile: avatar,
        name: "Abc Xyz",
        employment: "Engineer",
        emailId: "abc11@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    },
    {
        uniqueId:"uid12",
        profile: avatar,
        name: "Abc Xyz",
        employment: "Engineer",
        emailId: "abc12@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    },
    {
        uniqueId:"uid13",
        profile: avatar,
        name: "Abc Xyz",
        employment: "Engineer",
        emailId: "abc13@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    },
    {
        uniqueId:"uid14",
        profile: avatar,
        name: "Abc Xyz",
        employment: "Engineer",
        emailId: "abc14@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    },
    {
        uniqueId:"uid15",
        profile: avatar,
        name: "Abc Xyz",
        employment: "Engineer",
        emailId: "abc15@gmail.com",
        phoneNo: 7854526314,
        linkedInProfile: linkedIn,
    }
]

export default data;